import { doc, setDoc, query, where, getDocs, collection } from 'firebase/firestore';
import { auth, db } from '@/data/db'
import { EventFormData, EventModel } from "./models/event.model";

function mapFormDataToEventModel(formData: EventFormData): EventModel {
  // 1. Structure the schedule object
  const schedule = {
    startDate: formData.startDate,
    endDate: formData.endDate,
    startTime: formData.startTime,
    endTime: formData.endTime,
    timezone: formData.timezone,
    isRecurring: formData.isRecurring,
    recurrencePattern: formData.isRecurring ? formData.recurrenceType : null,
  };

  // 2. Structure the location object (mapping coordinates and flat fields safely)
  const location = {
    venueName: formData.venueName,
    address: formData.address,
    city: formData.city,
    country: "", // Add if available in your form later, otherwise defaults to model safe fallback
    coordinates: {
      latitude: formData.coordinates?.lat ?? 0,
      longitude: formData.coordinates?.lng ?? 0,
    },
    // Map virtual properties if it's virtual or hybrid
    meetingPlatform: formData.locationType !== 'physical' ? "Custom" : null, 
    meetingLink: formData.locationType !== 'physical' ? formData.videoUrl : null,
    meetingId: null,
    meetingPassword: null,
    parkingInfo: "",
    accessibilityInfo: "",
    nearbyHotels: [],
    nearbyRestaurants: [],
  };

  // 3. Structure the capacity object
  const capacity = {
    totalSeats: formData.totalSeats,
    reservedSeats: formData.reservedSeats,
    availableSeats: Math.max(0, formData.totalSeats - formData.reservedSeats),
    waitingListEnabled: formData.enableWaitingList,
    waitingListCapacity: formData.enableWaitingList ? 20 : 0, // Fallback default value
    maxRegistrationsPerUser: formData.maxTicketsPerPerson,
  };

  // 4. Transform CustomField frontend interface to backend customForm schema layout
  const customForm = formData.customFields.map((field) => ({
    fieldId: field.id,
    label: field.label,
    type: field.type,
    options: field.options || [],
    required: field.required,
    helpText: "",
  }));

  // 5. Structure the registration limits and setups
  const registration = {
    registrationOpenDate: "", // Set to current date or handle explicitly if added to form
    registrationCloseDate: formData.startDate, // Commonly defaults to the start date of the event
    requiresApproval: formData.requiresApproval,
    customForm: customForm,
    earlyBirdDeadline: "",
    groupRegistrationEnabled: formData.groupDiscount,
    groupDiscountEnabled: formData.groupDiscount,
  };

  // 6. Map TicketTiers from form to the expected pricing structures
  const pricing = {
    isFree: formData.ticketType === 'free',
    currency: "PKR", // Default application currency
    tiers: formData.ticketTiers.map((tier) => ({
      name: tier.name,
      price: formData.ticketType === 'free' ? 0 : tier.price,
      availableUntil: tier.availableUntil,
      seats: tier.seatsAvailable,
      description: tier.benefits,
    })),
    studentDiscount: {
      enabled: formData.studentDiscount,
      percentage: formData.studentDiscountPercent,
      requiresVerification: true,
    },
    groupDiscount: {
      enabled: formData.groupDiscount,
      minGroupSize: 5, // Set standard default step threshold
      percentage: formData.groupDiscountPercent,
    },
  };

  // 7. Calculate combined dates for the timestamps based on your parseDate logic
  const combineDateTime = (dateStr: string, timeStr: string): Date => {
    if (!dateStr) return new Date();
    const time = timeStr || "00:00";
    return new Date(`${dateStr}T${time}`);
  };

  // 8. Assemble raw object mirroring standard backend updates
  const rawModelPayload = {
    eventId: "", // Will be auto-generated by your backend system
    organizerId: "", // Pull this dynamically from your authentication context wrapper
    title: formData.eventTitle,
    description: formData.description,
    shortDescription: formData.shortDescription,
    category: formData.category,
    eventType: formData.eventType,
    format: formData.locationType,
    language: "en", 
    schedule: schedule,
    location: location,
    bannerImage: formData.bannerImage || "",
    galleryImages: formData.galleryImages,
    promoVideoUrl: formData.videoUrl,
    capacity: capacity,
    registration: registration,
    pricing: pricing,
    speakers: [], // Filled dynamically in an isolated speaker allocation pane
    agenda: [],    // Managed under advanced dynamic configurations
    vendorRequirements: [],
    teamMembers: [],
    status: formData.publishImmediately ? "published" : "draft",
    visibility: formData.visibility,
    accessCode: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: formData.publishImmediately ? new Date() : null,
    eventStartTime: combineDateTime(formData.startDate, formData.startTime),
    eventEndTime: combineDateTime(formData.endDate, formData.endTime),
    archivedAt: null,
    deletedAt: null,
  };

  // Return generated implementation via the class factory instance
  return EventModel.fromJson(rawModelPayload);
}

export const EventService = {

    async getEventByID(id: string) {
        console.log("In get event this is thte id i am searching for ", id);
        if (!id) { console.warn("id is nulll brooooo"); return null };

        const q = query(
            collection(db, "events"),
            where("id", "==", id)
        );
        const querySnapshot = await getDocs(q);
        if (querySnapshot.empty) {
            console.log("this event doesnt exist yet");
            return new EventModel({});
        }
        console.log("found itttt ", querySnapshot.docs[0].data());
        const event: EventModel = EventModel.fromJson(querySnapshot.docs[0].data());
        return event;



    },

    async getAllEventsByOrganizer(organizer_id: string) {
        const q = query(
            collection(db, "events"),
            where("organizerId", "==", organizer_id)
        );

        const querySnapshot = await getDocs(q);
        let arr: EventModel[] = [];

        querySnapshot.forEach((doc) => {
            console.log("in getALL events");
            console.log(doc.data());
            arr.push(EventModel.fromJson(doc.data()));
        });

        return arr;
    },
    async getRecentReg(event_id: string) {
        const q = query(collection(db, "registerations"), where("eventId", "==", event_id));
        const querySnapshot = await getDocs(q);
        let arr: EventModel[] = [];

        querySnapshot.forEach((doc) => {
            console.log(doc.data());
            arr.push(EventModel.fromJson(doc.data()));
        });

        return arr;

    },
    async create_event(formdata: EventFormData,organizer_id:string) {
        const event_to_be_added :EventModel = mapFormDataToEventModel(formdata); 
        event_to_be_added.organizerId = organizer_id;
        const docRef = doc(collection(db,"events"));
        const id_generated = docRef.id;
        event_to_be_added.id = id_generated;

        await setDoc(docRef,{...event_to_be_added});
        console.log(`Document successfully written with ID: ${id_generated}`);
    }
}