import { auth, db } from '@/data/db'
import { doc, setDoc, getDoc } from 'firebase/firestore';
import { Organizer } from './models/organizer.model';


function mapToOrganizer(item: any): Organizer {
  if (!item) {
    throw new Error("Cannot map an empty or null object to an Organizer.");
  }

  // 1. Initialize the class with required base identifiers
  const organizer = new Organizer(
    item.userId || "", 
    item.contact?.primaryEmail || "", 
    item.organization?.name || ""
  );

  // Overwrite the autogenerated constructor ID if a real one exists
  if (item.organizerId) {
    organizer.organizerId = item.organizerId;
  }

  // 2. Map Organization Details
  organizer.organization = {
    type: item.organization?.type || 'individual',
    name: item.organization?.name || organizer.organization.name,
    establishedYear: Number(item.organization?.establishedYear) || new Date().getFullYear(),
    description: item.organization?.description || '',
    logo: item.organization?.logo || '',
    coverImage: item.organization?.coverImage || ''
  };

  // 3. Map Contact Info
  organizer.contact = {
    primaryEmail: item.contact?.primaryEmail || organizer.contact.primaryEmail,
    primaryPhone: item.contact?.primaryPhone || '',
    socialMedia: item.contact?.socialMedia || {}
  };

  // 4. Map Address
  organizer.address = {
    officeAddress: item.address?.officeAddress || '',
    city: item.address?.city || '',
    country: item.address?.country || 'Pakistan',
    coordinates: {
      lat: Number(item.address?.coordinates?.lat) || 0,
      lng: Number(item.address?.coordinates?.lng) || 0
    }
  };

  // 5. Map Banking Details
  organizer.banking = {
    bankName: item.banking?.bankName || '',
    accountTitle: item.banking?.accountTitle || '',
    accountNumber: item.banking?.accountNumber || '',
    iban: item.banking?.iban || '',
    paymentMethods: Array.isArray(item.banking?.paymentMethods) ? item.banking.paymentMethods : [],
    payoutSchedule: item.banking?.payoutSchedule || 'weekly',
    minimumPayout: Number(item.banking?.minimumPayout) || 5000
  };

  // 6. Map Event Stats
  organizer.eventStats = {
    totalEventsCreated: Number(item.eventStats?.totalEventsCreated) || 0,
    publishedEvents: Number(item.eventStats?.publishedEvents) || 0,
    upcomingEvents: Number(item.eventStats?.upcomingEvents) || 0,
    completedEvents: Number(item.eventStats?.completedEvents) || 0,
    cancelledEvents: Number(item.eventStats?.cancelledEvents) || 0,
    totalAttendees: Number(item.eventStats?.totalAttendees) || 0,
    averageAttendeesPerEvent: Number(item.eventStats?.averageAttendeesPerEvent) || 0,
    totalRevenue: Number(item.eventStats?.totalRevenue) || 0,
    averageRating: Number(item.eventStats?.averageRating) ?? 5.0
  };

  // 7. Map Vendor Stats
  organizer.vendorStats = {
    totalVendorsHired: Number(item.vendorStats?.totalVendorsHired) || 0,
    repeatVendors: Number(item.vendorStats?.repeatVendors) || 0,
    averageVendorRating: Number(item.vendorStats?.averageVendorRating) || 0,
    totalSpentOnVendors: Number(item.vendorStats?.totalSpentOnVendors) || 0
  };

  // 8. Map Verification Status
  organizer.verification = {
    isVerified: Boolean(item.verification?.isVerified),
    verificationLevel: item.verification?.verificationLevel || 'bronze',
    documents: item.verification?.documents || {},
    badges: Array.isArray(item.verification?.badges) ? item.verification.badges : []
  };

  // 9. Map Settings
  organizer.settings = {
    autoPublishEvents: Boolean(item.settings?.autoPublishEvents),
    defaultEventSettings: {
      certificateTemplate: item.settings?.defaultEventSettings?.certificateTemplate || 'template_01',
      reminderDays: Array.isArray(item.settings?.defaultEventSettings?.reminderDays) 
        ? item.settings.defaultEventSettings.reminderDays.map(Number) 
        : [7, 1],
      allowWaitlist: item.settings?.defaultEventSettings?.allowWaitlist !== false, // Defaults to true if missing
      requireApproval: Boolean(item.settings?.defaultEventSettings?.requireApproval)
    },
    notificationPreferences: {
      newRegistrations: item.settings?.notificationPreferences?.newRegistrations !== false,
      newVendorQuotes: item.settings?.notificationPreferences?.newVendorQuotes !== false,
      paymentReceived: item.settings?.notificationPreferences?.paymentReceived !== false,
      eventReminders: item.settings?.notificationPreferences?.eventReminders !== false
    }
  };

  // 10. Map Subscription Plan
  organizer.plan = {
    type: item.plan?.type || 'free',
    features: Array.isArray(item.plan?.features) ? item.plan.features : [],
    expiresAt: item.plan?.expiresAt ? new Date(item.plan.expiresAt) : new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
    autoRenew: Boolean(item.plan?.autoRenew)
  };

  // 11. Map Timestamps (safely converting standard ISO strings or Firestore timestamps to JavaScript Dates)
  organizer.createdAt = item.createdAt ? new Date(item.createdAt.seconds ? item.createdAt.toDate() : item.createdAt) : new Date();
  organizer.updatedAt = item.updatedAt ? new Date(item.updatedAt.seconds ? item.updatedAt.toDate() : item.updatedAt) : new Date();
  organizer.lastActive = item.lastActive ? new Date(item.lastActive.seconds ? item.lastActive.toDate() : item.lastActive) : new Date();

  return organizer;
}

export const OrganizerService = {
  async getOrganizerById(id: String) {
    const docRef = doc(db, "organizer", id);
    const docSnap = await getDoc(docRef);
    
    return mapToOrganizer(docSnap.data());
  }
}

