export const mockVendors = [
  {
    vendorId: "V001",
    userId: "U006",
    businessName: "Perfect Catering Services",
    contact: {
      primaryPhone: "+923001234567",
      secondaryPhone: "+923001234568",
      businessEmail: "info@perfectcatering.pk",
      website: "https://perfectcatering.pk",
      address: {
        street: "123 Commercial Area Phase 4",
        city: "Lahore",
        country: "Pakistan",
        coordinates: { lat: 31.5204, lng: 74.3587 },
      },
    },
    serviceCategories: ["catering", "event_management"],
    portfolio: {
      images: [
        {
          url: "https://storage.events.com/portfolio/V001/img1.jpg",
          caption: "Techverse Conference Lunch Buffet",
          eventType: "conference",
          date: "2025-10-15",
        },
        {
          url: "https://storage.events.com/portfolio/V001/img2.jpg",
          caption: "Executive High Tea Setup",
          eventType: "workshop",
          date: "2026-02-10",
        },
      ],
      videos: ["https://storage.events.com/portfolio/V001/vid1.mp4"],
      clientTestimonials: [
        {
          clientName: "Arithmiks",
          testimonial:
            "Perfect Catering delivered exactly as promised. The food was warm and the staff was very professional during our annual corporate retreat.",
          rating: 5,
          eventDate: "2025-10-15",
        },
      ],
      pastEvents: ["evt_prev_01", "evt_prev_02"],
    },
    pricingPackages: [
      {
        packageId: "PKG001",
        name: "Standard Conference Box",
        description:
          "Individual boxed lunches perfect for quick conference breaks.",
        inclusions: ["Club Sandwich", "Fries", "Juice Box", "Brownie"],
        price: 850,
        minOrder: 50,
        customizationOptions: ["vegetarian", "gluten-free"],
      },
      {
        packageId: "PKG002",
        name: "Premium Buffet Spread",
        description: "Full buffet setup with chafing dishes and service staff.",
        inclusions: ["Chicken Karahi", "Biryani", "Naan", "Salad", "Trifle"],
        price: 2500,
        minOrder: 100,
        customizationOptions: ["spice_level", "dessert_choice"],
      },
    ],
    ratings: {
      averageRating: 4.8,
      totalReviews: 42,
      breakdown: {
        "5": 35,
        "4": 6,
        "3": 1,
        "2": 0,
        "1": 0,
      },
    },
    stats: {
      totalBookings: 85,
      completedBookings: 82,
      cancellationRate: 3.5,
      repeatClients: 25,
      totalRevenue: 12500000,
      avgResponseTime: "1 hour",
    },
    verification: {
      verified: true,
      verificationMethod: "document_review",
      verifiedAt: "2024-01-10T09:00:00Z",
      verificationBadges: ["top_rated", "food_safety_certified"],
    },
    settings: {
      autoAcceptQuotes: false,
      notificationPreferences: {
        newQuotes: true,
        bookingConfirmations: true,
        paymentReceipts: true,
        reviews: true,
      },
      commissionRate: 10,
    },
    status: "active",
    featured: true,
    createdAt: "2024-01-05T14:30:00Z",
    updatedAt: "2026-06-01T10:00:00Z",
    lastActive: "2026-06-15T18:00:00Z",
  },
  {
    vendorId: "V005",
    userId: "U007",
    businessName: "Sound & Vision Pro",
    contact: {
      primaryPhone: "+923219876543",
      secondaryPhone: "+923219876544",
      businessEmail: "bookings@soundvision.pk",
      website: "https://soundvision.pk",
      address: {
        street: "45 Tech Market, Gulberg",
        city: "Lahore",
        country: "Pakistan",
        coordinates: { lat: 31.5085, lng: 74.3487 },
      },
    },
    serviceCategories: ["av_equipment", "lighting"],
    portfolio: {
      images: [
        {
          url: "https://storage.events.com/portfolio/V005/av_setup1.jpg",
          caption: "Main Stage Hackathon Setup",
          eventType: "hackathon",
          date: "2026-01-20",
        },
      ],
      videos: [],
      clientTestimonials: [
        {
          clientName: "FAST-NUCES Events Society",
          testimonial:
            "Flawless audio execution. The wireless mics worked perfectly throughout the entire auditorium without any feedback issues.",
          rating: 5,
          eventDate: "2026-01-20",
        },
      ],
      pastEvents: ["evt_prev_04"],
    },
    pricingPackages: [
      {
        packageId: "PKG_AV_01",
        name: "Basic Seminar Kit",
        description: "Essential AV setup for small rooms.",
        inclusions: [
          "1 Projector (1080p)",
          "1 Projection Screen",
          "2 Wireless Mics",
          "Basic PA Speaker pair",
        ],
        price: 25000,
        minOrder: 1,
        customizationOptions: ["add_clicker", "add_lapel_mic"],
      },
      {
        packageId: "PKG_AV_02",
        name: "Auditorium Full System",
        description: "Comprehensive audio-visual solution for large halls.",
        inclusions: [
          "Dual 4K Projectors",
          "Line Array Speakers",
          "Digital Mixer Board",
          "6 Wireless Mics",
          "On-site Technician",
        ],
        price: 85000,
        minOrder: 1,
        customizationOptions: ["stage_lighting", "live_stream_camera"],
      },
    ],
    ratings: {
      averageRating: 4.5,
      totalReviews: 18,
      breakdown: {
        "5": 12,
        "4": 4,
        "3": 2,
        "2": 0,
        "1": 0,
      },
    },
    stats: {
      totalBookings: 35,
      completedBookings: 32,
      cancellationRate: 8.5,
      repeatClients: 10,
      totalRevenue: 2150000,
      avgResponseTime: "4 hours",
    },
    verification: {
      verified: true,
      verificationMethod: "manual_review",
      verifiedAt: "2025-03-15T11:00:00Z",
      verificationBadges: ["equipment_insured"],
    },
    settings: {
      autoAcceptQuotes: false,
      notificationPreferences: {
        newQuotes: true,
        bookingConfirmations: true,
        paymentReceipts: false,
        reviews: true,
      },
      commissionRate: 10,
    },
    status: "active",
    featured: false,
    createdAt: "2025-03-10T09:15:00Z",
    updatedAt: "2026-05-20T11:30:00Z",
    lastActive: "2026-06-14T09:45:00Z",
  },
  {
    vendorId: "V002",
    userId: "U008",
    businessName: "Blossom & Elegance Events",
    contact: {
      primaryPhone: "+923005556789",
      secondaryPhone: "+923005556790",
      businessEmail: "info@blossomevents.pk",
      website: "https://blossomevents.pk",
      address: {
        street: "78 Decoration Lane, Clifton",
        city: "Karachi",
        country: "Pakistan",
        coordinates: { lat: 24.7914, lng: 66.9917 },
      },
    },
    serviceCategories: ["decoration", "event_design"],
    portfolio: {
      images: [
        {
          url: "https://storage.events.com/portfolio/V002/dec1.jpg",
          caption: "Luxurious Wedding Venue Transformation",
          eventType: "wedding",
          date: "2026-04-15",
        },
      ],
      videos: [],
      clientTestimonials: [
        {
          clientName: "Elite Events Organizers",
          testimonial:
            "Their attention to detail and creative vision transformed our venue into a fairytale setting.",
          rating: 5,
          eventDate: "2026-04-15",
        },
      ],
      pastEvents: ["evt_prev_05", "evt_prev_06"],
    },
    pricingPackages: [
      {
        packageId: "PKG_DEC_01",
        name: "Classic Stage Decor",
        description: "Professional stage and entrance decoration.",
        inclusions: ["Stage backdrop", "Entrance arch", "Ambient lighting"],
        price: 85000,
        minOrder: 1,
        customizationOptions: ["custom_colors", "themed_elements"],
      },
      {
        packageId: "PKG_DEC_02",
        name: "Premium Floral Suite",
        description: "Comprehensive floral and botanical arrangements.",
        inclusions: [
          "Centerpieces",
          "Garlands",
          "Flower arches",
          "Specialty arrangements",
        ],
        price: 180000,
        minOrder: 1,
        customizationOptions: ["flower_selection", "seasonal_themes"],
      },
    ],
    ratings: {
      averageRating: 4.9,
      totalReviews: 31,
      breakdown: {
        "5": 28,
        "4": 3,
        "3": 0,
        "2": 0,
        "1": 0,
      },
    },
    stats: {
      totalBookings: 56,
      completedBookings: 55,
      cancellationRate: 1.8,
      repeatClients: 18,
      totalRevenue: 8900000,
      avgResponseTime: "2 hours",
    },
    verification: {
      verified: true,
      verificationMethod: "document_review",
      verifiedAt: "2025-06-20T14:00:00Z",
      verificationBadges: ["top_rated", "eco_friendly_certified"],
    },
    settings: {
      autoAcceptQuotes: false,
      notificationPreferences: {
        newQuotes: true,
        bookingConfirmations: true,
        paymentReceipts: true,
        reviews: true,
      },
      commissionRate: 12,
    },
    status: "active",
    featured: true,
    createdAt: "2025-02-15T10:30:00Z",
    updatedAt: "2026-06-10T15:20:00Z",
    lastActive: "2026-06-18T11:00:00Z",
  },
  {
    vendorId: "V003",
    userId: "U009",
    businessName: "Chef's Table Premium Catering",
    contact: {
      primaryPhone: "+923334445555",
      secondaryPhone: "+923334445556",
      businessEmail: "bookings@chefstable.pk",
      website: "https://chefstable.pk",
      address: {
        street: "456 Gourmet Avenue, DHA",
        city: "Karachi",
        country: "Pakistan",
        coordinates: { lat: 24.8195, lng: 67.0347 },
      },
    },
    serviceCategories: ["catering", "culinary_services"],
    portfolio: {
      images: [
        {
          url: "https://storage.events.com/portfolio/V003/catering1.jpg",
          caption: "Executive Corporate Lunch Setup",
          eventType: "corporate",
          date: "2026-05-20",
        },
      ],
      videos: ["https://storage.events.com/portfolio/V003/cooking_demo.mp4"],
      clientTestimonials: [
        {
          clientName: "Fortune 500 Company Pakistan",
          testimonial:
            "Exceptional culinary experience. Each dish was perfectly prepared and beautifully presented.",
          rating: 5,
          eventDate: "2026-05-20",
        },
      ],
      pastEvents: ["evt_prev_07", "evt_prev_08", "evt_prev_09"],
    },
    pricingPackages: [
      {
        packageId: "PKG_CAT_01",
        name: "Corporate Lunch Box",
        description: "Professional boxed lunch for business meetings.",
        inclusions: ["Sandwich", "Salad", "Dessert", "Beverage"],
        price: 750,
        minOrder: 50,
        customizationOptions: ["vegetarian", "dietary_requirements"],
      },
      {
        packageId: "PKG_CAT_02",
        name: "Gourmet Buffet",
        description: "Multi-course buffet with premium ingredients.",
        inclusions: ["3 main courses", "5 sides", "3 desserts", "Beverages"],
        price: 3500,
        minOrder: 100,
        customizationOptions: [
          "menu_customization",
          "dietary_special_requests",
        ],
      },
    ],
    ratings: {
      averageRating: 4.7,
      totalReviews: 48,
      breakdown: {
        "5": 40,
        "4": 7,
        "3": 1,
        "2": 0,
        "1": 0,
      },
    },
    stats: {
      totalBookings: 92,
      completedBookings: 90,
      cancellationRate: 2.2,
      repeatClients: 35,
      totalRevenue: 15600000,
      avgResponseTime: "1.5 hours",
    },
    verification: {
      verified: true,
      verificationMethod: "document_review",
      verifiedAt: "2024-12-01T09:30:00Z",
      verificationBadges: ["food_safety_certified", "top_rated"],
    },
    settings: {
      autoAcceptQuotes: false,
      notificationPreferences: {
        newQuotes: true,
        bookingConfirmations: true,
        paymentReceipts: true,
        reviews: true,
      },
      commissionRate: 10,
    },
    status: "active",
    featured: true,
    createdAt: "2024-11-15T08:00:00Z",
    updatedAt: "2026-06-15T12:45:00Z",
    lastActive: "2026-06-19T09:20:00Z",
  },
  {
    vendorId: "V004",
    userId: "U010",
    businessName: "Premium Venue Solutions",
    contact: {
      primaryPhone: "+923001112222",
      secondaryPhone: "+923001112223",
      businessEmail: "hello@premiumvenue.pk",
      website: "https://premiumvenue.pk",
      address: {
        street: "123 Business District, Blue Area",
        city: "Islamabad",
        country: "Pakistan",
        coordinates: { lat: 33.7298, lng: 73.1786 },
      },
    },
    serviceCategories: ["venue", "event_space"],
    portfolio: {
      images: [
        {
          url: "https://storage.events.com/portfolio/V004/venue1.jpg",
          caption: "Grand Ballroom Conference Setup",
          eventType: "conference",
          date: "2026-05-10",
        },
      ],
      videos: [],
      clientTestimonials: [
        {
          clientName: "Tech Innovation Summit",
          testimonial:
            "Fantastic venue with all the amenities. Staff was incredibly helpful and professional.",
          rating: 5,
          eventDate: "2026-05-10",
        },
      ],
      pastEvents: ["evt_prev_10", "evt_prev_11"],
    },
    pricingPackages: [
      {
        packageId: "PKG_VEN_01",
        name: "Meeting Room Package",
        description: "Single meeting room for 8-12 hours.",
        inclusions: ["Projector and screen", "WiFi", "Refreshments"],
        price: 25000,
        minOrder: 1,
        customizationOptions: ["catering_addon", "recording_setup"],
      },
      {
        packageId: "PKG_VEN_02",
        name: "Grand Ballroom Full Day",
        description: "Exclusive use of main ballroom with full amenities.",
        inclusions: [
          "Ballroom access",
          "4 meeting rooms",
          "Parking",
          "WiFi",
          "AV setup",
        ],
        price: 150000,
        minOrder: 1,
        customizationOptions: ["decoration_service", "catering_partners"],
      },
    ],
    ratings: {
      averageRating: 4.6,
      totalReviews: 24,
      breakdown: {
        "5": 18,
        "4": 5,
        "3": 1,
        "2": 0,
        "1": 0,
      },
    },
    stats: {
      totalBookings: 67,
      completedBookings: 65,
      cancellationRate: 3.0,
      repeatClients: 22,
      totalRevenue: 11200000,
      avgResponseTime: "2 hours",
    },
    verification: {
      verified: true,
      verificationMethod: "manual_review",
      verifiedAt: "2025-01-10T11:00:00Z",
      verificationBadges: ["venue_certified"],
    },
    settings: {
      autoAcceptQuotes: false,
      notificationPreferences: {
        newQuotes: true,
        bookingConfirmations: true,
        paymentReceipts: true,
        reviews: true,
      },
      commissionRate: 8,
    },
    status: "active",
    featured: true,
    createdAt: "2024-10-20T13:15:00Z",
    updatedAt: "2026-06-12T10:30:00Z",
    lastActive: "2026-06-18T14:20:00Z",
  },
];
